// Environment variable keys
export const ENV_KEYS = {
  // Database
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_NAME: 'DB_NAME',

  // JWT
  JWT_SECRET: 'JWT_SECRET',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  JWT_ACCESS_EXPIRATION: 'JWT_ACCESS_EXPIRATION',
  JWT_REFRESH_EXPIRATION: 'JWT_REFRESH_EXPIRATION',

  // Throttle/Rate Limiting
  THROTTLE_SHORT_LIMIT: 'THROTTLE_SHORT_LIMIT',
  THROTTLE_MEDIUM_LIMIT: 'THROTTLE_MEDIUM_LIMIT',
  THROTTLE_LONG_LIMIT: 'THROTTLE_LONG_LIMIT',

  // Application
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
} as const;
